### ISSUE TITLE
MVSX no sound

### ISSUE THREAD

**Issue by molnara** [acmeplus/RetroArch-ASP#1]
## Description

Load a rom and no sound.  I tried various options in the menu.

### Expected behavior

To hear sound

### Actual behavior

No sound

### Steps to reproduce the bug

1. Start retroarch
2. Load a rom

**Comment by acmeplus** [comment]
MVSX audio initialization is not performed by retroarch, the issue is that the initial audio volume setting is set up when the default MVSX menu starts taking into account the volume control. I suggest you start the regular MVSX menu, check the volume is at at desired level and then start retroarch. The volume should work then. As I mentioned before I don't own an MVSX but all other users have confirmed sound works fine.
